##### refer : https://qiita.com/wataling/items/fa8b74fa50d80b88aea3

server:
  port: 8090
  servlet:
    session:
      timeout: 2400

spring:
  profiles:
    active: localhost
    
---
spring:
  profiles: localhost
  thymeleaf:
    enabled: true
    cache: false 
  datasource:
    url: jdbc:postgresql://ec2-54-235-80-210.compute-1.amazonaws.com:5432/d1mqgs1pj7a10h
    username: jkanqmkgmmbddv
    password: a7b13eff3fdf0689fd6b6a510b3d9760dea0eaec8c307c5551a6f9b9761c40d8
    driver-class-name: org.postgresql.Driver
---
spring:
  profiles: docker
  thymeleaf:
    enabled: true
    cache: false 
  datasource:
#    url: jdbc:postgresql://warikan-postgres:5432/user1
    url: jdbc:postgresql://db-dev:5432/user1
    username: user1
    password: user1
    driver-class-name: org.postgresql.Driver

ymlsetting:
  host: http://localhost:8090
#  host: https://tatekae-simple.herokuapp.com
  