##### refer : https://qiita.com/wataling/items/fa8b74fa50d80b88aea3

server:
  port: 8090
  servlet:
    session:
      timeout: 2400

spring:
  profiles:
    active: localhost
    
---
spring:
  profiles: localhost
  thymeleaf:
    enabled: true
    cache: false 
---
spring:
  profiles: docker
  thymeleaf:
    enabled: true
    cache: false 
  datasource:
    url: jdbc:postgresql://db-dev:5432/user1
    username: user1
    password: user1
    driver-class-name: org.postgresql.Driver

ymlsetting:
  host: http://localhost:8090
  