server:
  port: 8090
  
spring:
  thymeleaf:
    enabled: true
    cache: false 
  datasource:
    url: jdbc:postgresql://ec2-54-235-80-210.compute-1.amazonaws.com:5432/d1mqgs1pj7a10h
    username: jkanqmkgmmbddv
    password: a7b13eff3fdf0689fd6b6a510b3d9760dea0eaec8c307c5551a6f9b9761c40d8
    driver-class-name: org.postgresql.Driver