version: 2
jobs:
  build:
#    docker:
#      - image: circleci/ruby:2.4.2-jessie-node
    machine: true
    steps:
      - checkout
#      - run: 
#          name: docker compose build
#          command: docker compose build
      - run: 
          name: pwd
          command: pwd
      - run: 
          name: ls
          command: ls -l
      - run: 
          name: mvn package -DskipTests
          command: mvn package -DskipTests
      - run: 
          name: docker compose up
          command: docker-compose up -d --build
      - run: 
          name: sleep 30 sec
          command: sleep 30s
      - run: 
          name: mvn test
          command: mvn test
      - run: 
          name: docker-compose down
          command: docker-compose down
          