version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
###   create jar file on circleci env .
      - run: 
          name: mvn package -DskipTests
          command: mvn package -DskipTests
###   create testing env from docker-compose file .
      - run: 
          name: docker compose up
          command: docker-compose up -d --build
      - run: 
          name: sleep 10 sec
          command: sleep 10s
###   run mvn test .
      - run: 
          name: mvn test
          command: mvn test
      - run: 
          name: docker-compose down
          command: docker-compose down
          